title: "daGrev.is"
permalink: "/:year/:month/:title"
markdown: "kramdown"
highlighter: "rouge"
url: "http://dagrev.is/"
author: "Raitis (daGrevis) Stengrevics"
author_bio: "Hacker, engineer and blogger"
paginate: 5
paginate_path: "page/:num"
