version: '3'

services:
  elastic:
    image: 'elasticsearch:6.6.0'
    volumes:
     - '/root/msks/elastic-data:/usr/share/elasticsearch/data'
    environment:
     - bootstrap.memory_lock=true
     - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
     - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always

  postgres:
    image: 'postgres'
    volumes:
     - '/root/msks/postgres-data:/var/lib/postgresql/data'
    links:
     - elastic
    restart: always

  msks:
    image: 'msks'
    volumes:
     - '/root/msks/config.toml:/usr/src/app/config.toml:ro'
     - '/root/msks/build-msks:/srv/msks:ro'
     - '/root/msks/build-developerslv:/srv/developerslv:ro'
    links:
     - elastic
     - postgres
    restart: always

  nginx:
    image: 'nginx:alpine'
    ports:
     - '80:80'
     - '443:443'
    volumes:
     - '/root/daGrev.is/nginx.conf:/etc/nginx/nginx.conf:ro'
     - '/root/daGrev.is/certs:/etc/letsencrypt:ro'
     - '/root/daGrev.is/certs-data:/data/letsencrypt:ro'
     - '/root/daGrev.is/_site:/srv/daGrev.is:ro'
     - '/root/msks/build-msks:/srv/msks:ro'
     - '/root/msks/build-developerslv:/srv/developerslv:ro'
    links:
     - msks
    restart: always

  bncr:
    container_name: bncr
    image: bncr
    restart: always
    volumes:
     - '/root/bncr/config.toml:/usr/src/app/config.toml:ro'
