version: '2'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
     - /etc/daGrev.is/nginx.conf:/etc/nginx/nginx.conf:ro
     - /etc/daGrev.is/.htpasswd:/etc/nginx/.htpasswd:ro
     - /srv/daGrev.is:/srv/daGrev.is:ro
     - ~/msks/build:/srv/msks:ro
     - ~/msks/developerslv:/srv/developerslv:ro
    ports:
     - '80:80'
    links:
     - rethink
     - msks
     - lounge
    restart: always

  rethink:
    container_name: rethink
    image: rethinkdb
    volumes:
     - ~/msks/rethink-data:/data
    restart: always

  msks:
    container_name: msks
    image: msks
    links:
     - rethink
    volumes:
     - ~/msks/config.toml:/usr/src/app/config.toml:ro
     - ~/msks/build:/srv/msks:ro
     - ~/msks/developerslv:/srv/developerslv:ro
    restart: always

  lounge:
    container_name: lounge
    image: mylounge # https://github.com/daGrevis/docker-thelounge
    command: lounge start
    volumes:
     - /etc/.lounge:/root/.lounge
    restart: always
