version: '2'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
     - /etc/daGrev.is/nginx.conf:/etc/nginx/nginx.conf:ro
     - /etc/daGrev.is/.htpasswd:/etc/nginx/.htpasswd:ro
     - /srv/daGrev.is:/srv/daGrev.is:ro
    ports:
     - '80:80'
    links:
     - cashout
    restart: always

  cashout:
    container_name: cashout
    image: cashout
    volumes:
     - /var/cashout:/var/cashout
     - /srv/cashout:/app/static
    environment:
      CASHOUT_DBPATH: /var/cashout/default.db
      CASHOUT_APPROOT: /cashout
    restart: always
