version: '2'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
     - /etc/daGrev.is/nginx.conf:/etc/nginx/nginx.conf:ro
     - /etc/daGrev.is/.htpasswd:/etc/nginx/.htpasswd:ro
     - /etc/daGrev.is/certs:/etc/letsencrypt:ro
     - /etc/daGrev.is/certs-data:/data/letsencrypt:ro
     - /srv/daGrev.is:/srv/daGrev.is:ro
     - ~/msks/build:/srv/msks:ro
     - ~/msks/developerslv:/srv/developerslv:ro
    ports:
     - 80:80
     - 443:443
    links:
     - glances
     - rethink
     - msks
     - lounge
    restart: always

  glances:
    container_name: glances
    image: docker.io/nicolargo/glances
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: 'host'
    environment:
     - GLANCES_OPT=-w --disable-amps
    restart: always

  rethink:
    container_name: rethink
    image: rethinkdb
    volumes:
     - ~/msks/rethink-data:/data
    restart: always

  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0
    volumes:
     - ~/msks/elastic-data:/usr/share/elasticsearch/data
    environment:
     - http.host=0.0.0.0
     - transport.host=127.0.0.1
     - bootstrap.memory_lock=true
     - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always

  msks:
    container_name: msks
    image: msks
    links:
     - rethink
     - elastic
    volumes:
     - ~/msks/config.toml:/usr/src/app/config.toml:ro
     - ~/msks/build:/srv/msks:ro
     - ~/msks/developerslv:/srv/developerslv:ro
    restart: always

  bncr:
    container_name: bncr
    image: bncr
    volumes:
     - ~/bncr/config.toml:/usr/src/app/config.toml:ro
    restart: always

  lounge:
    container_name: lounge
    image: mylounge # https://github.com/daGrevis/docker-thelounge
    command: lounge start
    volumes:
     - /etc/.lounge:/root/.lounge
    restart: always
