version: "3"

services:
  nginx:
    container_name: nginx
    image: "nginx:alpine"
    links:
      - msks
      - rethink
      - znc
      - lounge
      - glances
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "/etc/daGrev.is/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/etc/daGrev.is/.htpasswd:/etc/nginx/.htpasswd:ro"
      - "/etc/daGrev.is/certs:/etc/letsencrypt:ro"
      - "/etc/daGrev.is/certs-data:/data/letsencrypt:ro"
      - "/srv/daGrev.is:/srv/daGrev.is:ro"
      - "~/msks/build:/srv/msks:ro"
      - "~/msks/developerslv:/srv/developerslv:ro"

  msks:
    container_name: msks
    image: msks
    links:
      - rethink
      - elastic
    restart: always
    volumes:
      - "~/msks/config.toml:/usr/src/app/config.toml:ro"
      - "~/msks/build:/srv/msks:ro"
      - "~/msks/developerslv:/srv/developerslv:ro"

  bncr:
    container_name: bncr
    image: bncr
    restart: always
    volumes:
      - "~/bncr/config.toml:/usr/src/app/config.toml:ro"

  rethink:
    container_name: rethink
    image: rethinkdb
    restart: always
    volumes:
      - "~/msks/rethink-data:/data"

  elastic:
    container_name: elastic
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      bootstrap.memory_lock: "true"
      http.host: "0.0.0.0"
      transport.host: "127.0.0.1"
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0"
    restart: always
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - "~/msks/elastic-data:/usr/share/elasticsearch/data"

  znc:
    container_name: znc
    image: znc:slim
    ports:
      - "6697:6697"
    restart: always
    volumes:
      - "/etc/znc-data:/znc-data"

  lounge:
    command: "lounge start"
    container_name: lounge
    image: mylounge # https://github.com/daGrevis/docker-thelounge
    restart: always
    volumes:
      - "/etc/.lounge:/root/.lounge"

  glances:
    container_name: glances
    environment:
      - "GLANCES_OPT=-w --disable-amps"
    image: docker.io/nicolargo/glances
    pid: host
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
