version: '2'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
     - /etc/daGrev.is/nginx.conf:/etc/nginx/nginx.conf:ro
     - /etc/daGrev.is/.htpasswd:/etc/nginx/.htpasswd:ro
     - /srv/daGrev.is:/srv/daGrev.is:ro
     - /srv/svg-scene:/srv/svg-scene:ro
     - ~/msks/build:/srv/msks:ro
     - ~/developerslv/build:/srv/developerslv:ro
    ports:
     - '80:80'
    links:
     - lounge
     - rethink
     - msks-server
    restart: always

  lounge:
    container_name: lounge
    image: mylounge # https://github.com/daGrevis/docker-thelounge
    volumes:
     - /etc/.lounge:/root/.lounge
    command: lounge --private start
    restart: always

  rethink:
    container_name: rethink
    image: rethinkdb
    volumes:
     - ~/msks/rethink-data:/data
    restart: always

  msks-server:
    container_name: msks-server
    image: msks-server
    links:
      - rethink
    ports:
     - '3001:3001'
    environment:
      RETHINK_HOST: rethink
    restart: always

  msks-bot:
    container_name: msks-bot
    image: msks-bot
    links:
      - rethink
    volumes:
      - ~/msks/config.json:/usr/src/app/config.json:ro
    restart: always
