version: '2'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
     - /etc/daGrev.is/nginx.conf:/etc/nginx/nginx.conf:ro
     - /etc/daGrev.is/.htpasswd:/etc/nginx/.htpasswd:ro
     - /srv/daGrev.is:/srv/daGrev.is:ro
     - /srv/svg-scene:/srv/svg-scene:ro
    ports:
     - '80:80'
    links:
     - cashout
     - lounge
    restart: always

  cashout:
    container_name: cashout
    image: cashout
    volumes:
     - /var/cashout:/var/cashout
     - /srv/cashout:/app/static
    environment:
      CASHOUT_DBPATH: /var/cashout/default.db
      CASHOUT_APPROOT: /cashout
    restart: always

  lounge:
    container_name: lounge
    image: mylounge # https://github.com/daGrevis/docker-thelounge
    volumes:
     - /etc/.lounge:/root/.lounge
    ports:
     - '9000:9000'
    command: lounge --private start
    restart: always
